/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 public/meshes/terrain.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Euler } from '@react-three/fiber';

export default function GLTFModel({
  rotation
}: {
  rotation: Euler
}) {
  
  //@ts-ignore
  const { nodes, materials } = useGLTF('/gltf/ground-separated.gltf');

  return (
      //@ts-ignore
      <mesh geometry={nodes['ground-plane-baked-applied'].geometry} material={materials['Ground-baked']} rotation={rotation} receiveShadow needsUpdate />

  )
}

useGLTF.preload('/gltf/ground-separated.gltf')
