/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 public/meshes/terrain.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Euler } from '@react-three/fiber';

export default function GorseEmitter({rotation}: {rotation?: Euler}) {
  const { nodes, materials } = useGLTF('/gltf/gorse-emitter.gltf');

  return (
      <mesh geometry={nodes['gorse-emitter'].geometry} material={materials['Material.002']} rotation={rotation} receiveShadow needsUpdate scale={[1,1,1]} />
  )
}

useGLTF.preload('/gltf/gorse-emitter.gltf')
