/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 public/meshes/grass.gltf --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('meshes/grass-transformed.glb');
  return (
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} scale={0.1}/>
  )
}

useGLTF.preload('meshes/grass-transformed.glb')
